services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  api:
    build: .
    container_name: mcp-agent-api
    ports:
      - "8088:8080"
    env_file:
      - .env
    environment:
      - QDRANT_HOST=qdrant
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  qdrant_storage:
